import { Language, MusicTrack } from './types';

// --- Translations ---
export const TRANSLATIONS = {
  [Language.ES]: {
    splashDedication: "Dedicado a las personas que no disfrutan el día y sufren la noche.",
    navBreathing: "Respiración",
    navMusic: "Música",
    navHipnos: "Hipnos",
    navTengu: "Tengu",
    navSettings: "Ajustes",
    sectionBreathing: "Respiración Guiada",
    descBreathing: "Sincroniza tu respiración para reducir el cortisol y calmar el sistema nervioso.",
    sectionMusic: "Entorno Sonoro",
    descMusic: "Frecuencias binaurales y paisajes sonoros para inducir ondas cerebrales lentas.",
    descHipnos: "Asistente empático para resolver dudas sobre el sueño y calmar la ansiedad nocturna.",
    descTengu: "Planificador de rutinas nocturnas estrictas y personalizadas.",
    descSettings: "Personaliza tu experiencia, idioma y preferencias visuales.",
    inhale: "Inhalar",
    exhale: "Exhalar",
    hold: "Mantener",
    start: "Comenzar",
    stop: "Detener",
    categoryNature: "Sonidos Naturales",
    categoryMelody: "Melodías Relajantes",
    chatPlaceholder: "Escribe tu mensaje aquí...",
    hipnosIntro: "Soy Hipnos. Pregúntame sobre el sueño, insomnio o hábitos de descanso.",
    tenguIntro: "Soy Tengu. Dime tus horarios y hábitos, y crearé un plan de sueño para ti.",
    settingsLang: "Lenguaje",
    settingsTheme: "Tonalidad",
    settingsInfo: "Información",
    themeDark: "Cielo Nocturno",
    themeLight: "Claridad Diurna",
    hipnosReject1: "Lo siento, mi conocimiento se limita exclusivamente al mundo de los sueños y el descanso.",
    hipnosReject2: "Como guardián del sueño, solo puedo asistirte en temas relacionados con el descanso nocturno.",
    hipnosReject3: "Por favor, centrémonos en mejorar tu descanso. ¿Tienes alguna duda sobre el insomnio?",
    infoPlaceholder: "Aplicación Ad Somnum v1.0.0. Desarrollada para ayudar a conciliar el sueño.",
    // Tengu Form
    tenguLabelDinner: "Hora de Cena",
    tenguLabelBed: "Hora de Dormir",
    tenguLabelHabits: "Malos hábitos o problemas actuales",
    tenguPlaceholderHabits: "Ej: Uso el móvil en la cama, ceno muy pesado...",
    tenguBtnGenerate: "Generar Plan Nocturno",
    tenguBtnReset: "Crear Nuevo Plan",
    tenguResultTitle: "Tu Protocolo Nocturno",
    // Errors
    errorNoInternet: "No se detecta conexión a internet. La IA necesita red para funcionar.",
    errorGeneric: "Error al conectar con las estrellas...",
  },
  [Language.CA]: {
    splashDedication: "Dedicat a les persones que no gaudeixen del dia i pateixen la nit.",
    navBreathing: "Respiració",
    navMusic: "Música",
    navHipnos: "Hipnos",
    navTengu: "Tengu",
    navSettings: "Configuració",
    sectionBreathing: "Respiració Guiada",
    descBreathing: "Sincronitza la teva respiració per reduir el cortisol i calmar el sistema nerviós.",
    sectionMusic: "Entorn Sonor",
    descMusic: "Freqüències binaurals i paisatges sonors per induir ones cerebrals lentes.",
    descHipnos: "Assistent empàtic per resoldre dubtes sobre la son i calmar l'ansietat nocturna.",
    descTengu: "Planificador de rutines nocturnes estrictes i personalitzades.",
    descSettings: "Personalitza la teva experiència, idioma i preferències visuals.",
    inhale: "Inhala",
    exhale: "Exhala",
    hold: "Mantingues",
    start: "Començar",
    stop: "Aturar",
    categoryNature: "Sons Naturals",
    categoryMelody: "Melodies Relaxants",
    chatPlaceholder: "Escriu el teu missatge aquí...",
    hipnosIntro: "Sóc Hipnos. Pregunta'm sobre la son, l'insomni o hàbits de descans.",
    tenguIntro: "Sóc Tengu. Digues-me els teus horaris i et crearé un pla de son.",
    settingsLang: "Llengua",
    settingsTheme: "Tonalitat",
    settingsInfo: "Informació",
    themeDark: "Cel Nocturn",
    themeLight: "Claredat Diürna",
    hipnosReject1: "Ho sento, el meu coneixement es limita exclusivament al món dels somnis i el descans.",
    hipnosReject2: "Com a guardià del son, només puc assistir-te en temes relacionats amb el descans nocturn.",
    hipnosReject3: "Si us plau, centrem-nos en millorar el teu descans. Tens algun dubte sobre l'insomni?",
    infoPlaceholder: "Aplicació Ad Somnum v1.0.0. Desenvolupada per ajudar a agafar el son.",
    // Tengu Form
    tenguLabelDinner: "Hora de Sopar",
    tenguLabelBed: "Hora de Dormir",
    tenguLabelHabits: "Mals hàbits o problemes actuals",
    tenguPlaceholderHabits: "Ex: Faig servir el mòbil al llit, sopo molt pesat...",
    tenguBtnGenerate: "Generar Pla Nocturn",
    tenguBtnReset: "Crear Nou Pla",
    tenguResultTitle: "El teu Protocol Nocturn",
    // Errors
    errorNoInternet: "No es detecta connexió a internet. La IA necessita xarxa per funcionar.",
    errorGeneric: "Error al connectar amb les estrelles...",
  },
  [Language.EN]: {
    splashDedication: "Dedicated to those who do not enjoy the day and suffer the night.",
    navBreathing: "Breathing",
    navMusic: "Music",
    navHipnos: "Hipnos",
    navTengu: "Tengu",
    navSettings: "Settings",
    sectionBreathing: "Guided Breathing",
    descBreathing: "Synchronize your breath to reduce cortisol and calm the nervous system.",
    sectionMusic: "Sound Environment",
    descMusic: "Binaural frequencies and soundscapes designed to induce slow brain waves.",
    descHipnos: "Empathetic assistant to answer sleep questions and soothe night anxiety.",
    descTengu: "Strict planner for personalized evening routines.",
    descSettings: "Customize your experience, language, and visual preferences.",
    inhale: "Inhale",
    exhale: "Exhale",
    hold: "Hold",
    start: "Start",
    stop: "Stop",
    categoryNature: "Nature Sounds",
    categoryMelody: "Relaxing Melodies",
    chatPlaceholder: "Type your message here...",
    hipnosIntro: "I am Hipnos. Ask me about sleep, insomnia, or rest habits.",
    tenguIntro: "I am Tengu. Tell me your schedule and habits, and I will create a sleep plan.",
    settingsLang: "Language",
    settingsTheme: "Tone",
    settingsInfo: "Information",
    themeDark: "Night Sky",
    themeLight: "Morning Clarity",
    hipnosReject1: "I'm sorry, my knowledge is strictly limited to sleep and rest.",
    hipnosReject2: "As a guardian of sleep, I can only assist you with topics related to nightly rest.",
    hipnosReject3: "Please, let's focus on improving your rest. Do you have any questions about insomnia?",
    infoPlaceholder: "Ad Somnum App v1.0.0. Developed to help you fall asleep.",
    // Tengu Form
    tenguLabelDinner: "Dinner Time",
    tenguLabelBed: "Bedtime",
    tenguLabelHabits: "Bad habits or current issues",
    tenguPlaceholderHabits: "Ex: Using phone in bed, heavy meals...",
    tenguBtnGenerate: "Generate Night Plan",
    tenguBtnReset: "Create New Plan",
    tenguResultTitle: "Your Night Protocol",
    // Errors
    errorNoInternet: "No internet connection. AI needs network to function.",
    errorGeneric: "Error connecting to the stars...",
  },
  [Language.FR]: {
    splashDedication: "Dédié à ceux qui ne profitent pas du jour et souffrent la nuit.",
    navBreathing: "Respiration",
    navMusic: "Musique",
    navHipnos: "Hipnos",
    navTengu: "Tengu",
    navSettings: "Paramètres",
    sectionBreathing: "Respiration Guidée",
    descBreathing: "Synchronisez votre respiration pour réduire le cortisol et calmer le système nerveux.",
    sectionMusic: "Environnement Sonore",
    descMusic: "Fréquences binaurales et paysages sonores pour induire des ondes cérébrales lentes.",
    descHipnos: "Assistant empathique pour répondre aux questions sur le sommeil et apaiser l'anxiété.",
    descTengu: "Planificateur strict pour des routines nocturnes personnalisées.",
    descSettings: "Personnalisez votre expérience, la langue et les préférences visuelles.",
    inhale: "Inspirer",
    exhale: "Expirer",
    hold: "Tenir",
    start: "Commencer",
    stop: "Arrêter",
    categoryNature: "Sons Naturels",
    categoryMelody: "Mélodies Relaxantes",
    chatPlaceholder: "Écrivez votre message ici...",
    hipnosIntro: "Je suis Hipnos. Interrogez-moi sur le sommeil, l'insomnie ou les habitudes.",
    tenguIntro: "Je suis Tengu. Donnez-moi vos horaires et je créerai un plan de sommeil.",
    settingsLang: "Langue",
    settingsTheme: "Tonalité",
    settingsInfo: "Information",
    themeDark: "Ciel Nocturne",
    themeLight: "Clarté Diurne",
    hipnosReject1: "Désolé, mes connaissances se limitent strictement au monde du sommeil.",
    hipnosReject2: "En tant que gardien du sommeil, je ne peux vous aider que sur des sujets liés au repos.",
    hipnosReject3: "S'il vous plaît, concentrons-nous sur l'amélioration de votre repos.",
    infoPlaceholder: "Application Ad Somnum v1.0.0. Développée pour aider à trouver le sommeil.",
    // Tengu Form
    tenguLabelDinner: "Heure du Dîner",
    tenguLabelBed: "Heure du Coucher",
    tenguLabelHabits: "Mauvaises habitudes ou problèmes",
    tenguPlaceholderHabits: "Ex: Téléphone au lit, repas lourds...",
    tenguBtnGenerate: "Générer Plan Nocturne",
    tenguBtnReset: "Créer Nouveau Plan",
    tenguResultTitle: "Votre Protocole Nocturne",
    // Errors
    errorNoInternet: "Pas de connexion internet. L'IA a besoin du réseau.",
    errorGeneric: "Erreur de connexion aux étoiles...",
  },
  [Language.DE]: {
    splashDedication: "Gewidmet denen, die den Tag nicht genießen und die Nacht erleiden.",
    navBreathing: "Atmung",
    navMusic: "Musik",
    navHipnos: "Hipnos",
    navTengu: "Tengu",
    navSettings: "Einstellungen",
    sectionBreathing: "Geführte Atmung",
    descBreathing: "Synchronisieren Sie Ihre Atmung, um Cortisol zu reduzieren und das Nervensystem zu beruhigen.",
    sectionMusic: "Klangumgebung",
    descMusic: "Binaurale Frequenzen und Klanglandschaften, um langsame Gehirnwellen zu induzieren.",
    descHipnos: "Empathischer Assistent, um Schlafprobleme zu klären und nächtliche Ängste zu lindern.",
    descTengu: "Strenger Planer für personalisierte Abendroutinen.",
    descSettings: "Passen Sie Ihr Erlebnis, Ihre Sprache und visuellen Vorlieben an.",
    inhale: "Einatmen",
    exhale: "Ausatmen",
    hold: "Halten",
    start: "Starten",
    stop: "Stoppen",
    categoryNature: "Naturgeräusche",
    categoryMelody: "Entspannende Melodien",
    chatPlaceholder: "Geben Sie hier Ihre Nachricht ein...",
    hipnosIntro: "Ich bin Hipnos. Fragen Sie mich nach Schlaf, Schlaflosigkeit oder Gewohnheiten.",
    tenguIntro: "Ich bin Tengu. Sagen Sie mir Ihre Zeiten, und ich erstelle einen Schlafplan.",
    settingsLang: "Sprache",
    settingsTheme: "Tonalität",
    settingsInfo: "Information",
    themeDark: "Nachthimmel",
    themeLight: "Tagesklarheit",
    hipnosReject1: "Tut mir leid, mein Wissen beschränkt sich ausschließlich auf Schlaf und Ruhe.",
    hipnosReject2: "Als Wächter des Schlafes kann ich Ihnen nur bei Themen helfen, die die nächtliche Ruhe betreffen.",
    hipnosReject3: "Bitte konzentrieren wir uns auf die Verbesserung Ihrer Ruhe.",
    infoPlaceholder: "Ad Somnum App v1.0.0. Entwickelt, um beim Einschlafen zu helfen.",
    // Tengu Form
    tenguLabelDinner: "Abendessen",
    tenguLabelBed: "Schlafenszeit",
    tenguLabelHabits: "Schlechte Gewohnheiten oder Probleme",
    tenguPlaceholderHabits: "Bsp: Telefon im Bett, schweres Essen...",
    tenguBtnGenerate: "Nachtplan Generieren",
    tenguBtnReset: "Neuen Plan Erstellen",
    tenguResultTitle: "Ihr Nachtprotokoll",
    // Errors
    errorNoInternet: "Keine Internetverbindung.",
    errorGeneric: "Fehler beim Verbinden mit den Sternen...",
  },
};

// --- Music Data ---
// Ensure you have these files in your public/audio folder: 1.mp3, 2.mp3, etc.
export const MUSIC_DATA: MusicTrack[] = [
  // Nature Sounds
  { id: 1, title: "Lluvia Suave (Soft Rain)", category: "nature", hzDescription: "Pink Noise Spectrum", url: "/audio/1.mp3" },
  { id: 2, title: "Olas del Océano (Ocean Waves)", category: "nature", hzDescription: "0.1 Hz Rhythm", url: "/audio/2.mp3" },
  { id: 3, title: "Viento en el Bosque (Forest Wind)", category: "nature", hzDescription: "White Noise", url: "/audio/3.mp3" },
  { id: 4, title: "Fuego de Chimenea (Crackling Fire)", category: "nature", hzDescription: "Low Frequency Warmth", url: "/audio/4.mp3" },
  { id: 5, title: "Grillos Nocturnos (Night Crickets)", category: "nature", hzDescription: "High Frequency Masking", url: "/audio/5.mp3" },
  { id: 6, title: "Arroyo de Montaña (Mountain Stream)", category: "nature", hzDescription: "Consistent Flow", url: "/audio/6.mp3" },
  { id: 7, title: "Tormenta Lejana (Distant Thunder)", category: "nature", hzDescription: "Deep Bass 40Hz", url: "/audio/7.mp3" },
  { id: 8, title: "Viento Ártico (Arctic Wind)", category: "nature", hzDescription: "Brown Noise", url: "/audio/8.mp3" },
  { id: 9, title: "Selva Húmeda (Rainforest)", category: "nature", hzDescription: "Ambient Texture", url: "/audio/9.mp3" },
  { id: 10, title: "Bajo el Agua (Underwater)", category: "nature", hzDescription: "Muffled Low Hz", url: "/audio/10.mp3" },
  
  // Melodies
  { id: 11, title: "Ondas Delta (Delta Waves)", category: "melody", hzDescription: "0.5 - 4 Hz", url: "/audio/11.mp3" },
  { id: 12, title: "Sueño Profundo (Deep Sleep)", category: "melody", hzDescription: "432 Hz", url: "/audio/12.mp3" },
  { id: 13, title: "Piano Lunar (Moon Piano)", category: "melody", hzDescription: "528 Hz", url: "/audio/13.mp3" },
  { id: 14, title: "Viaje Theta (Theta Journey)", category: "melody", hzDescription: "4 - 7 Hz", url: "/audio/14.mp3" },
  { id: 15, title: "Flauta Zen (Zen Flute)", category: "melody", hzDescription: "Natural Resonance", url: "/audio/15.mp3" },
  { id: 16, title: "Cuencos Tibetanos (Tibetan Bowls)", category: "melody", hzDescription: "Harmonic Series", url: "/audio/16.mp3" },
  { id: 17, title: "Noche Cósmica (Cosmic Night)", category: "melody", hzDescription: "Binaural Beats", url: "/audio/17.mp3" },
  { id: 18, title: "Respiración Sonora (Sonic Breath)", category: "melody", hzDescription: "Slow Tempo 60bpm", url: "/audio/18.mp3" },
  { id: 19, title: "Cuna de Estrellas (Star Cradle)", category: "melody", hzDescription: "Soft Synth Pad", url: "/audio/19.mp3" },
  { id: 20, title: "Silencio Blanco (White Silence)", category: "melody", hzDescription: "Drone 174 Hz", url: "/audio/20.mp3" },
];